
version: '3.1'

services:

  # MySQL
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gamerplus
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
    volumes:
      - "/Users/shniu/git/github/middleware-eco/db/playground/master:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/my.cnf"
    ports:
      - "3306:3306"

  # Web Client For MySQL
  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080


  # https://hub.docker.com/r/bitnami/redis/
  # sudo docker exec -it redis /bin/bash
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=111111
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    volumes:
      - "/Users/shniu/git/github/middleware-eco/db/playground/redis:/bitnami/redis"
      # - '/path/to/your_redis.conf:/opt/bitnami/redis/etc/redis.conf'

# volumes:
#   db-data:
