version: '3.1'

services:

  # MySQL
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fix
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
    volumes:
      - "db-data:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/my.cnf"
    ports:
      - "3306:3306"

  # Web Client For MySQL
  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080

volumes:
  db-data:
